BUCKET=devopswithmarcel.org
.PHONY: build deploy-infra deploy-site

build:
	sam build

deploy-infra:
	sam build && sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset

deploy-site:
	aws s3 sync ./resume-site s3://$(BUCKET)

push-to-github:
	@if [ -z "$(MESSAGE)" ]; then \
		echo "No commit message provided. Use: make push-to-github MESSAGE='Your commit message'"; \
		exit 1; \
	fi
	git add .
	git commit -m "$(MESSAGE)"
	git push origin main


