name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r tests/requirements.txt

    - name: Run tests
      run: |
        pytest tests/integration/test_api_processing.py

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Only deploy if tests pass

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Docker (for SAM CLI build container)
      uses: docker/setup-buildx-action@v3

    - name: Verify AWS SAM CLI
      run: sam --version

    - name: Build Lambda function using SAM (in Docker container)
      run: |
        sam build --use-container

    - name: Deploy Lambda function to AWS
      run: |
        sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM --region us-east-1 --no-fail-on-empty-changeset 


# sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM
       
