name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9 from deadsnakes repository
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt update
        sudo apt install -y python3.9 python3.9-distutils python3.9-venv
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
        python3 --version

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r tests/requirements.txt

    - name: Run tests
      run: |
        pytest tests/integration/test_api_processing.py

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:   
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Verify AWS SAM CLI installation
      run: |
        sam --version

    - name: Build Lambda function with SAM
      run: |
        sam build

    - name: Deploy Lambda function to AWS
      run: |
        sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM
